blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/unsubmail/unsubmail/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/unsubmail/unsubmail/blob/main/README.md
    about: Read the project documentation
